services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookstore.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookstore.settings
      - key: PYTHON_VERSION
        value: 3.11
